### ISSUE TITLE
No Emmet snippets

### ISSUE THREAD

**Issue by gvescu** [craigmaslowski/vscode-erb#1]
Hello.

When I'm editing my html.erb file in Ruby ERB mode, there's no Emmet snippets. Tab just... Well, add a tab space.

**Comment by craigmaslowski** [comment]
I really don't think this extension is at fault. It just tells VS Code to load a set of syntax highlighting rules. There is no code of any sort in it. Most likely, the Emmet snippets just aren't configured to work with .html.erb files.

Try uninstalling this extension, and see if you can insert Emmet snippets in .html.erb files.

**Comment by gvescu** [comment]
Reinstalling didn't worked.

That's weird. It must be a bug with VSCode. There should be something on the extension manifest that "enables" Emmet. I'll take a look.

Sorry for the inconvenience :)

**Comment by craigmaslowski** [comment]
Right...I forgot VS Code included Emmet support by default. My suspicions were confirmed though. I uninstalled the erb syntax extension from my copy and Emmet support doesn't work in .html.erb files. It looks like they only enabled it for certain file types. You might want to  [open a feature request](https://visualstudio.uservoice.com/forums/293070-visual-studio-code) or piggy back on [this request](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/11707866-emmet-not-working-in-template-language-like-twig-o).
